package cn.wtu.zld.protoPOJO;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MyMessage.proto

public final class MyMessage {
  private MyMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ParaMeterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ParaMeter)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ParaMeter.ParamType paraMeter_Type = 1;</code>
     * @return The enum numeric value on the wire for paraMeterType.
     */
    int getParaMeterTypeValue();
    /**
     * <code>.ParaMeter.ParamType paraMeter_Type = 1;</code>
     * @return The paraMeterType.
     */
    MyMessage.ParaMeter.ParamType getParaMeterType();

    /**
     * <code>int32 intData = 2;</code>
     * @return Whether the intData field is set.
     */
    boolean hasIntData();
    /**
     * <code>int32 intData = 2;</code>
     * @return The intData.
     */
    int getIntData();

    /**
     * <code>string stringData = 3;</code>
     * @return Whether the stringData field is set.
     */
    boolean hasStringData();
    /**
     * <code>string stringData = 3;</code>
     * @return The stringData.
     */
    java.lang.String getStringData();
    /**
     * <code>string stringData = 3;</code>
     * @return The bytes for stringData.
     */
    com.google.protobuf.ByteString
        getStringDataBytes();

    public MyMessage.ParaMeter.DataTypeCase getDataTypeCase();
  }
  /**
   * <pre>
   *定义我们的参数对象
   * </pre>
   *
   * Protobuf type {@code ParaMeter}
   */
  public static final class ParaMeter extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ParaMeter)
      ParaMeterOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ParaMeter.newBuilder() to construct.
    private ParaMeter(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ParaMeter() {
      paraMeterType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ParaMeter();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ParaMeter(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              paraMeterType_ = rawValue;
              break;
            }
            case 16: {
              dataType_ = input.readInt32();
              dataTypeCase_ = 2;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              dataTypeCase_ = 3;
              dataType_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MyMessage.internal_static_ParaMeter_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MyMessage.internal_static_ParaMeter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MyMessage.ParaMeter.class, MyMessage.ParaMeter.Builder.class);
    }

    /**
     * <pre>
     *通过枚举提供数据类型判断
     * </pre>
     *
     * Protobuf enum {@code ParaMeter.ParamType}
     */
    public enum ParamType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>intType = 0;</code>
       */
      intType(0),
      /**
       * <code>stringType = 1;</code>
       */
      stringType(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>intType = 0;</code>
       */
      public static final int intType_VALUE = 0;
      /**
       * <code>stringType = 1;</code>
       */
      public static final int stringType_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ParamType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static ParamType forNumber(int value) {
        switch (value) {
          case 0: return intType;
          case 1: return stringType;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ParamType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ParamType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ParamType>() {
              public ParamType findValueByNumber(int number) {
                return ParamType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return MyMessage.ParaMeter.getDescriptor().getEnumTypes().get(0);
      }

      private static final ParamType[] VALUES = values();

      public static ParamType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ParamType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ParaMeter.ParamType)
    }

    private int dataTypeCase_ = 0;
    private java.lang.Object dataType_;
    public enum DataTypeCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      INTDATA(2),
      STRINGDATA(3),
      DATATYPE_NOT_SET(0);
      private final int value;
      private DataTypeCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataTypeCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataTypeCase forNumber(int value) {
        switch (value) {
          case 2: return INTDATA;
          case 3: return STRINGDATA;
          case 0: return DATATYPE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataTypeCase
    getDataTypeCase() {
      return DataTypeCase.forNumber(
          dataTypeCase_);
    }

    public static final int PARAMETER_TYPE_FIELD_NUMBER = 1;
    private int paraMeterType_;
    /**
     * <code>.ParaMeter.ParamType paraMeter_Type = 1;</code>
     * @return The enum numeric value on the wire for paraMeterType.
     */
    @java.lang.Override public int getParaMeterTypeValue() {
      return paraMeterType_;
    }
    /**
     * <code>.ParaMeter.ParamType paraMeter_Type = 1;</code>
     * @return The paraMeterType.
     */
    @java.lang.Override public MyMessage.ParaMeter.ParamType getParaMeterType() {
      @SuppressWarnings("deprecation")
      MyMessage.ParaMeter.ParamType result = MyMessage.ParaMeter.ParamType.valueOf(paraMeterType_);
      return result == null ? MyMessage.ParaMeter.ParamType.UNRECOGNIZED : result;
    }

    public static final int INTDATA_FIELD_NUMBER = 2;
    /**
     * <code>int32 intData = 2;</code>
     * @return Whether the intData field is set.
     */
    @java.lang.Override
    public boolean hasIntData() {
      return dataTypeCase_ == 2;
    }
    /**
     * <code>int32 intData = 2;</code>
     * @return The intData.
     */
    @java.lang.Override
    public int getIntData() {
      if (dataTypeCase_ == 2) {
        return (java.lang.Integer) dataType_;
      }
      return 0;
    }

    public static final int STRINGDATA_FIELD_NUMBER = 3;
    /**
     * <code>string stringData = 3;</code>
     * @return Whether the stringData field is set.
     */
    public boolean hasStringData() {
      return dataTypeCase_ == 3;
    }
    /**
     * <code>string stringData = 3;</code>
     * @return The stringData.
     */
    public java.lang.String getStringData() {
      java.lang.Object ref = "";
      if (dataTypeCase_ == 3) {
        ref = dataType_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (dataTypeCase_ == 3) {
          dataType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string stringData = 3;</code>
     * @return The bytes for stringData.
     */
    public com.google.protobuf.ByteString
        getStringDataBytes() {
      java.lang.Object ref = "";
      if (dataTypeCase_ == 3) {
        ref = dataType_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (dataTypeCase_ == 3) {
          dataType_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (paraMeterType_ != MyMessage.ParaMeter.ParamType.intType.getNumber()) {
        output.writeEnum(1, paraMeterType_);
      }
      if (dataTypeCase_ == 2) {
        output.writeInt32(
            2, (int)((java.lang.Integer) dataType_));
      }
      if (dataTypeCase_ == 3) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, dataType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (paraMeterType_ != MyMessage.ParaMeter.ParamType.intType.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, paraMeterType_);
      }
      if (dataTypeCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(
              2, (int)((java.lang.Integer) dataType_));
      }
      if (dataTypeCase_ == 3) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, dataType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MyMessage.ParaMeter)) {
        return super.equals(obj);
      }
      MyMessage.ParaMeter other = (MyMessage.ParaMeter) obj;

      if (paraMeterType_ != other.paraMeterType_) return false;
      if (!getDataTypeCase().equals(other.getDataTypeCase())) return false;
      switch (dataTypeCase_) {
        case 2:
          if (getIntData()
              != other.getIntData()) return false;
          break;
        case 3:
          if (!getStringData()
              .equals(other.getStringData())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PARAMETER_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + paraMeterType_;
      switch (dataTypeCase_) {
        case 2:
          hash = (37 * hash) + INTDATA_FIELD_NUMBER;
          hash = (53 * hash) + getIntData();
          break;
        case 3:
          hash = (37 * hash) + STRINGDATA_FIELD_NUMBER;
          hash = (53 * hash) + getStringData().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MyMessage.ParaMeter parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MyMessage.ParaMeter parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MyMessage.ParaMeter parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MyMessage.ParaMeter parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MyMessage.ParaMeter parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MyMessage.ParaMeter parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MyMessage.ParaMeter parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MyMessage.ParaMeter parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MyMessage.ParaMeter parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MyMessage.ParaMeter parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MyMessage.ParaMeter parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MyMessage.ParaMeter parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MyMessage.ParaMeter prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *定义我们的参数对象
     * </pre>
     *
     * Protobuf type {@code ParaMeter}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ParaMeter)
        MyMessage.ParaMeterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MyMessage.internal_static_ParaMeter_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MyMessage.internal_static_ParaMeter_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MyMessage.ParaMeter.class, MyMessage.ParaMeter.Builder.class);
      }

      // Construct using MyMessage.ParaMeter.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        paraMeterType_ = 0;

        dataTypeCase_ = 0;
        dataType_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MyMessage.internal_static_ParaMeter_descriptor;
      }

      @java.lang.Override
      public MyMessage.ParaMeter getDefaultInstanceForType() {
        return MyMessage.ParaMeter.getDefaultInstance();
      }

      @java.lang.Override
      public MyMessage.ParaMeter build() {
        MyMessage.ParaMeter result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public MyMessage.ParaMeter buildPartial() {
        MyMessage.ParaMeter result = new MyMessage.ParaMeter(this);
        result.paraMeterType_ = paraMeterType_;
        if (dataTypeCase_ == 2) {
          result.dataType_ = dataType_;
        }
        if (dataTypeCase_ == 3) {
          result.dataType_ = dataType_;
        }
        result.dataTypeCase_ = dataTypeCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MyMessage.ParaMeter) {
          return mergeFrom((MyMessage.ParaMeter)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MyMessage.ParaMeter other) {
        if (other == MyMessage.ParaMeter.getDefaultInstance()) return this;
        if (other.paraMeterType_ != 0) {
          setParaMeterTypeValue(other.getParaMeterTypeValue());
        }
        switch (other.getDataTypeCase()) {
          case INTDATA: {
            setIntData(other.getIntData());
            break;
          }
          case STRINGDATA: {
            dataTypeCase_ = 3;
            dataType_ = other.dataType_;
            onChanged();
            break;
          }
          case DATATYPE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MyMessage.ParaMeter parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MyMessage.ParaMeter) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataTypeCase_ = 0;
      private java.lang.Object dataType_;
      public DataTypeCase
          getDataTypeCase() {
        return DataTypeCase.forNumber(
            dataTypeCase_);
      }

      public Builder clearDataType() {
        dataTypeCase_ = 0;
        dataType_ = null;
        onChanged();
        return this;
      }


      private int paraMeterType_ = 0;
      /**
       * <code>.ParaMeter.ParamType paraMeter_Type = 1;</code>
       * @return The enum numeric value on the wire for paraMeterType.
       */
      @java.lang.Override public int getParaMeterTypeValue() {
        return paraMeterType_;
      }
      /**
       * <code>.ParaMeter.ParamType paraMeter_Type = 1;</code>
       * @param value The enum numeric value on the wire for paraMeterType to set.
       * @return This builder for chaining.
       */
      public Builder setParaMeterTypeValue(int value) {
        
        paraMeterType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.ParaMeter.ParamType paraMeter_Type = 1;</code>
       * @return The paraMeterType.
       */
      @java.lang.Override
      public MyMessage.ParaMeter.ParamType getParaMeterType() {
        @SuppressWarnings("deprecation")
        MyMessage.ParaMeter.ParamType result = MyMessage.ParaMeter.ParamType.valueOf(paraMeterType_);
        return result == null ? MyMessage.ParaMeter.ParamType.UNRECOGNIZED : result;
      }
      /**
       * <code>.ParaMeter.ParamType paraMeter_Type = 1;</code>
       * @param value The paraMeterType to set.
       * @return This builder for chaining.
       */
      public Builder setParaMeterType(MyMessage.ParaMeter.ParamType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        paraMeterType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ParaMeter.ParamType paraMeter_Type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearParaMeterType() {
        
        paraMeterType_ = 0;
        onChanged();
        return this;
      }

      /**
       * <code>int32 intData = 2;</code>
       * @return Whether the intData field is set.
       */
      public boolean hasIntData() {
        return dataTypeCase_ == 2;
      }
      /**
       * <code>int32 intData = 2;</code>
       * @return The intData.
       */
      public int getIntData() {
        if (dataTypeCase_ == 2) {
          return (java.lang.Integer) dataType_;
        }
        return 0;
      }
      /**
       * <code>int32 intData = 2;</code>
       * @param value The intData to set.
       * @return This builder for chaining.
       */
      public Builder setIntData(int value) {
        dataTypeCase_ = 2;
        dataType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 intData = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIntData() {
        if (dataTypeCase_ == 2) {
          dataTypeCase_ = 0;
          dataType_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>string stringData = 3;</code>
       * @return Whether the stringData field is set.
       */
      @java.lang.Override
      public boolean hasStringData() {
        return dataTypeCase_ == 3;
      }
      /**
       * <code>string stringData = 3;</code>
       * @return The stringData.
       */
      @java.lang.Override
      public java.lang.String getStringData() {
        java.lang.Object ref = "";
        if (dataTypeCase_ == 3) {
          ref = dataType_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (dataTypeCase_ == 3) {
            dataType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string stringData = 3;</code>
       * @return The bytes for stringData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getStringDataBytes() {
        java.lang.Object ref = "";
        if (dataTypeCase_ == 3) {
          ref = dataType_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (dataTypeCase_ == 3) {
            dataType_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string stringData = 3;</code>
       * @param value The stringData to set.
       * @return This builder for chaining.
       */
      public Builder setStringData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  dataTypeCase_ = 3;
        dataType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string stringData = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearStringData() {
        if (dataTypeCase_ == 3) {
          dataTypeCase_ = 0;
          dataType_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string stringData = 3;</code>
       * @param value The bytes for stringData to set.
       * @return This builder for chaining.
       */
      public Builder setStringDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        dataTypeCase_ = 3;
        dataType_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ParaMeter)
    }

    // @@protoc_insertion_point(class_scope:ParaMeter)
    private static final MyMessage.ParaMeter DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MyMessage.ParaMeter();
    }

    public static MyMessage.ParaMeter getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ParaMeter>
        PARSER = new com.google.protobuf.AbstractParser<ParaMeter>() {
      @java.lang.Override
      public ParaMeter parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ParaMeter(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ParaMeter> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ParaMeter> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public MyMessage.ParaMeter getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MesssageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Messsage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *参数个数
     * </pre>
     *
     * <code>int32 length = 1;</code>
     * @return The length.
     */
    int getLength();

    /**
     * <pre>
     *方法名称
     * </pre>
     *
     * <code>string methodName = 2;</code>
     * @return The methodName.
     */
    java.lang.String getMethodName();
    /**
     * <pre>
     *方法名称
     * </pre>
     *
     * <code>string methodName = 2;</code>
     * @return The bytes for methodName.
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    /**
     * <pre>
     *参数数组
     * </pre>
     *
     * <code>repeated .ParaMeter paraMeters = 3;</code>
     */
    java.util.List<MyMessage.ParaMeter> 
        getParaMetersList();
    /**
     * <pre>
     *参数数组
     * </pre>
     *
     * <code>repeated .ParaMeter paraMeters = 3;</code>
     */
    MyMessage.ParaMeter getParaMeters(int index);
    /**
     * <pre>
     *参数数组
     * </pre>
     *
     * <code>repeated .ParaMeter paraMeters = 3;</code>
     */
    int getParaMetersCount();
    /**
     * <pre>
     *参数数组
     * </pre>
     *
     * <code>repeated .ParaMeter paraMeters = 3;</code>
     */
    java.util.List<? extends MyMessage.ParaMeterOrBuilder> 
        getParaMetersOrBuilderList();
    /**
     * <pre>
     *参数数组
     * </pre>
     *
     * <code>repeated .ParaMeter paraMeters = 3;</code>
     */
    MyMessage.ParaMeterOrBuilder getParaMetersOrBuilder(
        int index);
  }
  /**
   * <pre>
   *定义我们传输的数据内容
   * </pre>
   *
   * Protobuf type {@code Messsage}
   */
  public static final class Messsage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Messsage)
      MesssageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Messsage.newBuilder() to construct.
    private Messsage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Messsage() {
      methodName_ = "";
      paraMeters_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Messsage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Messsage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              length_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              methodName_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                paraMeters_ = new java.util.ArrayList<MyMessage.ParaMeter>();
                mutable_bitField0_ |= 0x00000001;
              }
              paraMeters_.add(
                  input.readMessage(MyMessage.ParaMeter.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          paraMeters_ = java.util.Collections.unmodifiableList(paraMeters_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MyMessage.internal_static_Messsage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MyMessage.internal_static_Messsage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MyMessage.Messsage.class, MyMessage.Messsage.Builder.class);
    }

    public static final int LENGTH_FIELD_NUMBER = 1;
    private int length_;
    /**
     * <pre>
     *参数个数
     * </pre>
     *
     * <code>int32 length = 1;</code>
     * @return The length.
     */
    @java.lang.Override
    public int getLength() {
      return length_;
    }

    public static final int METHODNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object methodName_;
    /**
     * <pre>
     *方法名称
     * </pre>
     *
     * <code>string methodName = 2;</code>
     * @return The methodName.
     */
    @java.lang.Override
    public java.lang.String getMethodName() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        methodName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *方法名称
     * </pre>
     *
     * <code>string methodName = 2;</code>
     * @return The bytes for methodName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAMETERS_FIELD_NUMBER = 3;
    private java.util.List<MyMessage.ParaMeter> paraMeters_;
    /**
     * <pre>
     *参数数组
     * </pre>
     *
     * <code>repeated .ParaMeter paraMeters = 3;</code>
     */
    @java.lang.Override
    public java.util.List<MyMessage.ParaMeter> getParaMetersList() {
      return paraMeters_;
    }
    /**
     * <pre>
     *参数数组
     * </pre>
     *
     * <code>repeated .ParaMeter paraMeters = 3;</code>
     */
    @java.lang.Override
    public java.util.List<? extends MyMessage.ParaMeterOrBuilder> 
        getParaMetersOrBuilderList() {
      return paraMeters_;
    }
    /**
     * <pre>
     *参数数组
     * </pre>
     *
     * <code>repeated .ParaMeter paraMeters = 3;</code>
     */
    @java.lang.Override
    public int getParaMetersCount() {
      return paraMeters_.size();
    }
    /**
     * <pre>
     *参数数组
     * </pre>
     *
     * <code>repeated .ParaMeter paraMeters = 3;</code>
     */
    @java.lang.Override
    public MyMessage.ParaMeter getParaMeters(int index) {
      return paraMeters_.get(index);
    }
    /**
     * <pre>
     *参数数组
     * </pre>
     *
     * <code>repeated .ParaMeter paraMeters = 3;</code>
     */
    @java.lang.Override
    public MyMessage.ParaMeterOrBuilder getParaMetersOrBuilder(
        int index) {
      return paraMeters_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (length_ != 0) {
        output.writeInt32(1, length_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(methodName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, methodName_);
      }
      for (int i = 0; i < paraMeters_.size(); i++) {
        output.writeMessage(3, paraMeters_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (length_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, length_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(methodName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, methodName_);
      }
      for (int i = 0; i < paraMeters_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, paraMeters_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MyMessage.Messsage)) {
        return super.equals(obj);
      }
      MyMessage.Messsage other = (MyMessage.Messsage) obj;

      if (getLength()
          != other.getLength()) return false;
      if (!getMethodName()
          .equals(other.getMethodName())) return false;
      if (!getParaMetersList()
          .equals(other.getParaMetersList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getLength();
      hash = (37 * hash) + METHODNAME_FIELD_NUMBER;
      hash = (53 * hash) + getMethodName().hashCode();
      if (getParaMetersCount() > 0) {
        hash = (37 * hash) + PARAMETERS_FIELD_NUMBER;
        hash = (53 * hash) + getParaMetersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MyMessage.Messsage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MyMessage.Messsage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MyMessage.Messsage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MyMessage.Messsage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MyMessage.Messsage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MyMessage.Messsage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MyMessage.Messsage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MyMessage.Messsage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MyMessage.Messsage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MyMessage.Messsage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MyMessage.Messsage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MyMessage.Messsage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MyMessage.Messsage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *定义我们传输的数据内容
     * </pre>
     *
     * Protobuf type {@code Messsage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Messsage)
        MyMessage.MesssageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MyMessage.internal_static_Messsage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MyMessage.internal_static_Messsage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MyMessage.Messsage.class, MyMessage.Messsage.Builder.class);
      }

      // Construct using MyMessage.Messsage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getParaMetersFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        length_ = 0;

        methodName_ = "";

        if (paraMetersBuilder_ == null) {
          paraMeters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          paraMetersBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MyMessage.internal_static_Messsage_descriptor;
      }

      @java.lang.Override
      public MyMessage.Messsage getDefaultInstanceForType() {
        return MyMessage.Messsage.getDefaultInstance();
      }

      @java.lang.Override
      public MyMessage.Messsage build() {
        MyMessage.Messsage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public MyMessage.Messsage buildPartial() {
        MyMessage.Messsage result = new MyMessage.Messsage(this);
        int from_bitField0_ = bitField0_;
        result.length_ = length_;
        result.methodName_ = methodName_;
        if (paraMetersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            paraMeters_ = java.util.Collections.unmodifiableList(paraMeters_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.paraMeters_ = paraMeters_;
        } else {
          result.paraMeters_ = paraMetersBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MyMessage.Messsage) {
          return mergeFrom((MyMessage.Messsage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MyMessage.Messsage other) {
        if (other == MyMessage.Messsage.getDefaultInstance()) return this;
        if (other.getLength() != 0) {
          setLength(other.getLength());
        }
        if (!other.getMethodName().isEmpty()) {
          methodName_ = other.methodName_;
          onChanged();
        }
        if (paraMetersBuilder_ == null) {
          if (!other.paraMeters_.isEmpty()) {
            if (paraMeters_.isEmpty()) {
              paraMeters_ = other.paraMeters_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureParaMetersIsMutable();
              paraMeters_.addAll(other.paraMeters_);
            }
            onChanged();
          }
        } else {
          if (!other.paraMeters_.isEmpty()) {
            if (paraMetersBuilder_.isEmpty()) {
              paraMetersBuilder_.dispose();
              paraMetersBuilder_ = null;
              paraMeters_ = other.paraMeters_;
              bitField0_ = (bitField0_ & ~0x00000001);
              paraMetersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getParaMetersFieldBuilder() : null;
            } else {
              paraMetersBuilder_.addAllMessages(other.paraMeters_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MyMessage.Messsage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MyMessage.Messsage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int length_ ;
      /**
       * <pre>
       *参数个数
       * </pre>
       *
       * <code>int32 length = 1;</code>
       * @return The length.
       */
      @java.lang.Override
      public int getLength() {
        return length_;
      }
      /**
       * <pre>
       *参数个数
       * </pre>
       *
       * <code>int32 length = 1;</code>
       * @param value The length to set.
       * @return This builder for chaining.
       */
      public Builder setLength(int value) {
        
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *参数个数
       * </pre>
       *
       * <code>int32 length = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLength() {
        
        length_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object methodName_ = "";
      /**
       * <pre>
       *方法名称
       * </pre>
       *
       * <code>string methodName = 2;</code>
       * @return The methodName.
       */
      public java.lang.String getMethodName() {
        java.lang.Object ref = methodName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *方法名称
       * </pre>
       *
       * <code>string methodName = 2;</code>
       * @return The bytes for methodName.
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        java.lang.Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *方法名称
       * </pre>
       *
       * <code>string methodName = 2;</code>
       * @param value The methodName to set.
       * @return This builder for chaining.
       */
      public Builder setMethodName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        methodName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *方法名称
       * </pre>
       *
       * <code>string methodName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMethodName() {
        
        methodName_ = getDefaultInstance().getMethodName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *方法名称
       * </pre>
       *
       * <code>string methodName = 2;</code>
       * @param value The bytes for methodName to set.
       * @return This builder for chaining.
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        methodName_ = value;
        onChanged();
        return this;
      }

      private java.util.List<MyMessage.ParaMeter> paraMeters_ =
        java.util.Collections.emptyList();
      private void ensureParaMetersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          paraMeters_ = new java.util.ArrayList<MyMessage.ParaMeter>(paraMeters_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          MyMessage.ParaMeter, MyMessage.ParaMeter.Builder, MyMessage.ParaMeterOrBuilder> paraMetersBuilder_;

      /**
       * <pre>
       *参数数组
       * </pre>
       *
       * <code>repeated .ParaMeter paraMeters = 3;</code>
       */
      public java.util.List<MyMessage.ParaMeter> getParaMetersList() {
        if (paraMetersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(paraMeters_);
        } else {
          return paraMetersBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *参数数组
       * </pre>
       *
       * <code>repeated .ParaMeter paraMeters = 3;</code>
       */
      public int getParaMetersCount() {
        if (paraMetersBuilder_ == null) {
          return paraMeters_.size();
        } else {
          return paraMetersBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *参数数组
       * </pre>
       *
       * <code>repeated .ParaMeter paraMeters = 3;</code>
       */
      public MyMessage.ParaMeter getParaMeters(int index) {
        if (paraMetersBuilder_ == null) {
          return paraMeters_.get(index);
        } else {
          return paraMetersBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *参数数组
       * </pre>
       *
       * <code>repeated .ParaMeter paraMeters = 3;</code>
       */
      public Builder setParaMeters(
          int index, MyMessage.ParaMeter value) {
        if (paraMetersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParaMetersIsMutable();
          paraMeters_.set(index, value);
          onChanged();
        } else {
          paraMetersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *参数数组
       * </pre>
       *
       * <code>repeated .ParaMeter paraMeters = 3;</code>
       */
      public Builder setParaMeters(
          int index, MyMessage.ParaMeter.Builder builderForValue) {
        if (paraMetersBuilder_ == null) {
          ensureParaMetersIsMutable();
          paraMeters_.set(index, builderForValue.build());
          onChanged();
        } else {
          paraMetersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *参数数组
       * </pre>
       *
       * <code>repeated .ParaMeter paraMeters = 3;</code>
       */
      public Builder addParaMeters(MyMessage.ParaMeter value) {
        if (paraMetersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParaMetersIsMutable();
          paraMeters_.add(value);
          onChanged();
        } else {
          paraMetersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *参数数组
       * </pre>
       *
       * <code>repeated .ParaMeter paraMeters = 3;</code>
       */
      public Builder addParaMeters(
          int index, MyMessage.ParaMeter value) {
        if (paraMetersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParaMetersIsMutable();
          paraMeters_.add(index, value);
          onChanged();
        } else {
          paraMetersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *参数数组
       * </pre>
       *
       * <code>repeated .ParaMeter paraMeters = 3;</code>
       */
      public Builder addParaMeters(
          MyMessage.ParaMeter.Builder builderForValue) {
        if (paraMetersBuilder_ == null) {
          ensureParaMetersIsMutable();
          paraMeters_.add(builderForValue.build());
          onChanged();
        } else {
          paraMetersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *参数数组
       * </pre>
       *
       * <code>repeated .ParaMeter paraMeters = 3;</code>
       */
      public Builder addParaMeters(
          int index, MyMessage.ParaMeter.Builder builderForValue) {
        if (paraMetersBuilder_ == null) {
          ensureParaMetersIsMutable();
          paraMeters_.add(index, builderForValue.build());
          onChanged();
        } else {
          paraMetersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *参数数组
       * </pre>
       *
       * <code>repeated .ParaMeter paraMeters = 3;</code>
       */
      public Builder addAllParaMeters(
          java.lang.Iterable<? extends MyMessage.ParaMeter> values) {
        if (paraMetersBuilder_ == null) {
          ensureParaMetersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, paraMeters_);
          onChanged();
        } else {
          paraMetersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *参数数组
       * </pre>
       *
       * <code>repeated .ParaMeter paraMeters = 3;</code>
       */
      public Builder clearParaMeters() {
        if (paraMetersBuilder_ == null) {
          paraMeters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          paraMetersBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *参数数组
       * </pre>
       *
       * <code>repeated .ParaMeter paraMeters = 3;</code>
       */
      public Builder removeParaMeters(int index) {
        if (paraMetersBuilder_ == null) {
          ensureParaMetersIsMutable();
          paraMeters_.remove(index);
          onChanged();
        } else {
          paraMetersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *参数数组
       * </pre>
       *
       * <code>repeated .ParaMeter paraMeters = 3;</code>
       */
      public MyMessage.ParaMeter.Builder getParaMetersBuilder(
          int index) {
        return getParaMetersFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *参数数组
       * </pre>
       *
       * <code>repeated .ParaMeter paraMeters = 3;</code>
       */
      public MyMessage.ParaMeterOrBuilder getParaMetersOrBuilder(
          int index) {
        if (paraMetersBuilder_ == null) {
          return paraMeters_.get(index);  } else {
          return paraMetersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *参数数组
       * </pre>
       *
       * <code>repeated .ParaMeter paraMeters = 3;</code>
       */
      public java.util.List<? extends MyMessage.ParaMeterOrBuilder> 
           getParaMetersOrBuilderList() {
        if (paraMetersBuilder_ != null) {
          return paraMetersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(paraMeters_);
        }
      }
      /**
       * <pre>
       *参数数组
       * </pre>
       *
       * <code>repeated .ParaMeter paraMeters = 3;</code>
       */
      public MyMessage.ParaMeter.Builder addParaMetersBuilder() {
        return getParaMetersFieldBuilder().addBuilder(
            MyMessage.ParaMeter.getDefaultInstance());
      }
      /**
       * <pre>
       *参数数组
       * </pre>
       *
       * <code>repeated .ParaMeter paraMeters = 3;</code>
       */
      public MyMessage.ParaMeter.Builder addParaMetersBuilder(
          int index) {
        return getParaMetersFieldBuilder().addBuilder(
            index, MyMessage.ParaMeter.getDefaultInstance());
      }
      /**
       * <pre>
       *参数数组
       * </pre>
       *
       * <code>repeated .ParaMeter paraMeters = 3;</code>
       */
      public java.util.List<MyMessage.ParaMeter.Builder> 
           getParaMetersBuilderList() {
        return getParaMetersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          MyMessage.ParaMeter, MyMessage.ParaMeter.Builder, MyMessage.ParaMeterOrBuilder> 
          getParaMetersFieldBuilder() {
        if (paraMetersBuilder_ == null) {
          paraMetersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              MyMessage.ParaMeter, MyMessage.ParaMeter.Builder, MyMessage.ParaMeterOrBuilder>(
                  paraMeters_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          paraMeters_ = null;
        }
        return paraMetersBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Messsage)
    }

    // @@protoc_insertion_point(class_scope:Messsage)
    private static final MyMessage.Messsage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MyMessage.Messsage();
    }

    public static MyMessage.Messsage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Messsage>
        PARSER = new com.google.protobuf.AbstractParser<Messsage>() {
      @java.lang.Override
      public Messsage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Messsage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Messsage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Messsage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public MyMessage.Messsage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ParaMeter_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ParaMeter_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Messsage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Messsage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017MyMessage.proto\"\230\001\n\tParaMeter\022,\n\016paraM" +
      "eter_Type\030\001 \001(\0162\024.ParaMeter.ParamType\022\021\n" +
      "\007intData\030\002 \001(\005H\000\022\024\n\nstringData\030\003 \001(\tH\000\"(" +
      "\n\tParamType\022\013\n\007intType\020\000\022\016\n\nstringType\020\001" +
      "B\n\n\010dataType\"N\n\010Messsage\022\016\n\006length\030\001 \001(\005" +
      "\022\022\n\nmethodName\030\002 \001(\t\022\036\n\nparaMeters\030\003 \003(\013" +
      "2\n.ParaMeterB\013B\tMyMessageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ParaMeter_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ParaMeter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ParaMeter_descriptor,
        new java.lang.String[] { "ParaMeterType", "IntData", "StringData", "DataType", });
    internal_static_Messsage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Messsage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Messsage_descriptor,
        new java.lang.String[] { "Length", "MethodName", "ParaMeters", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
